### ISSUE TITLE
Travis Failing for all of the latest PRs

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/PublicLab.Editor#439]
I see most of the recent PRs are all failing. Any help is highly appreciated.

Error
```
$ grunt build
/home/travis/build/publiclab/PublicLab.Editor/node_modules/grunt/node_modules/mkdirp/index.js:4
const {mkdirpNative, mkdirpNativeSync} = require('./lib/mkdirp-native.js')
```

```
0.29s$ grunt build
/home/travis/build/publiclab/PublicLab.Editor/node_modules/grunt/node_modules/mkdirp/lib/opts-arg.js:7
    opts = { mode: 0o777 & (~process.umask()), fs, ...opts }
                                                   ^^^
```

```
 grunt build
/home/travis/build/publiclab/PublicLab.Editor/node_modules/grunt/node_modules/mkdirp/lib/opts-arg.js:7
    opts = { mode: 0o777 & (~process.umask()), fs, ...opts }
                                                   ^^^
SyntaxError: Unexpected token ...
  at createScript (vm.js:53:10)
  at Object.runInThisContext (vm.js:95:10)
  at Module._compile (module.js:543:28)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (/home/travis/build/publiclab/PublicLab.Editor/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/travis/build/publiclab/PublicLab.Editor/node_modules/grunt/node_modules/mkdirp/index.js:1:79)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (/home/travis/build/publiclab/PublicLab.Editor/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/travis/build/publiclab/PublicLab.Editor/node_modules/grunt/lib/grunt/file.js:20:14)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (/home/travis/build/publiclab/PublicLab.Editor/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at gRequire (/home/travis/build/publiclab/PublicLab.Editor/node_modules/grunt/lib/grunt.js:14:24)
  at Object.<anonymous> (/home/travis/build/publiclab/PublicLab.Editor/node_modules/grunt/lib/grunt.js:28:1)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/travis/build/publiclab/PublicLab.Editor/node_modules/grunt/node_modules/grunt-cli/bin/grunt:44:1)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/travis/build/publiclab/PublicLab.Editor/node_modules/grunt/bin/grunt:3:1)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.runMain (module.js:605:10)
  at run (bootstrap_node.js:427:7)
  at startup (bootstrap_node.js:151:9)
  at bootstrap_node.js:542:3
```

**Comment by cesswairimu** [comment]
@gauravano @nstjean @crisner @emilyashley any ideas?

**Comment by VladimirMikulic** [comment]
@cesswairimu the dependency uses object restructuring (`...`) which is not supported on Node < 8.3 version. Since we run tests on Node 5, 6, 7 it fails.

**Comment by VladimirMikulic** [comment]
Upgrading the Node version would be appreciated.

**Comment by cesswairimu** [comment]
Thanks @VladimirMikulic

**Comment by cesswairimu** [comment]
@keshav234156 take a look

**Comment by VladimirMikulic** [comment]
JS is welcome anytime :)

**Comment by HarshKhandeparkar** [comment]
Hi guys. Congrats on fixing this. But I would this fix as a workaround rather than a fix. I think not upgrading grunt is not good practice. You should always use the latest version of a package.

Also, nodejs version <8 support is stopped. I think we should support only version 8 and 10 (and 12 in the future). We have done that in ImageSequencer.

Node 8 and above support ES6 features that are supported even in the browsers and have become standard by now. Using old versions of nodejs and old features of javascript is not advisable.

If we desperately need support for older nodejs versions, we will have to write the code with new features, in node 8/10 and use [Babel](https://babeljs.io/) to downgrade the features for use in older browsers/older nodejs versions.

Not keeping dependencies/nodejs up to date is one rabbit hole you wouldn't want to go in.

Thank you!

**Comment by VladimirMikulic** [comment]
@HarshKhandeparkar couldn't agree more!

**Comment by keshav234156** [comment]
@HarshKhandeparkar I also agree with you .let's change it to 8 and 10 as of now

**Comment by cesswairimu** [comment]
Great everyone...should we open another issue for the fix :point_up:  or keep this open?

**Comment by keshav234156** [comment]
@cesswairimu made the changes in the same PR

**Comment by cesswairimu** [comment]
Great, thanks, I have pinged Jeff/Emily to merge
